### ISSUE TITLE
Motion Sidebar Endless Loading Icon

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#169]
After the motion has loaded the loading icon often just sticks around loading/pending

**Comment by jalafel** [comment]
I'm not sure how to recreate this, but it's running and event broadcast atm that seems to be unreliable. For now, I've added an interval that will run every 300ms for 5 times and it will set it off. 

This obviously is not a good fix, one way to go about implementing this in a more robust way is to create a loading directive that watches for the variable change across services, but that will take me me some time, so I'm leaving this open, but there is a shit fix:

3709db60e6b2d7c6bc849d07647a3eceb37221e2

**Comment by jalafel** [comment]
Switched event broadcasting with an interval emit to a global scope value that changes. 62cf341
I don't think this is the right way to do things, still, because you are still filling up the rootscope. Fiddled around with creating a factory for this and it isn't working as expected. But I will spend some more time on this.
