### ISSUE TITLE
Sending multiple requests to SettingsController doesn't work

### ISSUE THREAD

**Issue by jessicaquynh** [IserveU/IserveU#421]
Last key req not being set in settings.json
![screen shot 2016-10-28 at 1 07 09 pm](https://cloud.githubusercontent.com/assets/12400507/19815135/7b919276-9d0f-11e6-8116-225715407b06.png)
<img width="473" alt="screen shot 2016-10-28 at 1 06 18 pm" src="https://cloud.githubusercontent.com/assets/12400507/19815138/7d9bbcae-9d0f-11e6-97e7-645e67b27cde.png">
<img width="459" alt="screen shot 2016-10-28 at 1 06 22 pm" src="https://cloud.githubusercontent.com/assets/12400507/19815171/a0879b02-9d0f-11e6-9f1b-4fbe3229ec0d.png">

![screen shot 2016-10-28 at 1 06 34 pm](https://cloud.githubusercontent.com/assets/12400507/19815156/8e775902-9d0f-11e6-9eb5-b71b047bef44.png)

**Comment by jessicaquynh** [comment]
Seems to be an inverse issue of the previous one. Unable to set hte last key.

**Comment by psaunders** [comment]
You can only set one at a time. I can't see the URL

**Comment by jessicaquynh** [comment]
I am sending in 3 different requests with the key name and the value key, I'll reset my settings.json but this is happening whenever I send in muliple requests. The last key is always not set. It's funky behaviour.

**Comment by jessicaquynh** [comment]
The url's are on the side: /site.address, /site.twitter, /site.facebook

**Comment by psaunders** [comment]
Well it needs to be /api/setting/site.name

I wrote this test to recreate the behavior and it passes
https://github.com/IserveU/IserveU/pull/423/commits/572e6a2f57ff396a6486dc15194ab4b9b8534829

**Comment by psaunders** [comment]
If it's just occasionally I'd guess it's a race condition because the way the field works is it sets the whole field. When Laravel saves other fields (like a name) it does an intelligent update and only saves the fields that have actually changed which hides (or makes irrelevant) race conditions. Whereas because these fields are all in the same field one will overwrite the other if it gets saved first.
The easiest solution would be for the front end to queue updates, the most basic form of that would be disabling/putting a grey overlay on the page while it waits for the 200 from the server
A more complex one would be to push onto a queue the changes for values that exist in a JSON field.

The backend solutions to this would be enabling request throttling (like one request on this route every 10 seconds) but that is a little dumb because sometimes the server is going to be able to get it done in a few seconds. The other option would be to queue requests to change these settings with a queue worker running a specific queue just for these settings, however as we know queues are their own problem because everyone testing the software would need to run a queue and queue worker for the effect to be seen.

**Comment by psaunders** [comment]
The same system applied to user preferences should be applied here, making sure that one setting is changed at once and possibly queuing/locking the changes until the previous one completed
